var math_question = {
  "exportTime": "2025-09-23T12:51:38.308Z",
  "description": "数学题库数据",
  "questions": [
    {
      "id": 1757645039353,
      "title": "已经周长求面积",
      "content": "已知三角形周长为 12，其内角角平分线的交点到三角形三边的距离之和为 6，则三角形的面积为？",
      "answer": "# 💡解析\n## 分析\n本题先根据角平分线的性质得到交点到三边距离相等，再利用三角形面积公式，将三角形面积转化为与三边和以及该距离相关的式子，进而求出三角形面积。\n## 详解\n1. **作出辅助线并确定距离关系**\n    - 已知三角形内角角平分线的交点，设\\(\\triangle ABC\\)的内角平分线交于点\\(O\\)。\n    - 为了利用角平分线的性质以及计算三角形面积，作\\(OD\\perp AB\\)于点\\(D\\)，\\(OE\\perp BC\\)于点\\(E\\)，\\(OF\\perp AC\\)于点\\(F\\)。\n    - 根据角平分线的性质：角平分线上的点到角两边的距离相等，可知\\(OD = OE = OF\\)。\n    - 又已知内角角平分线的交点到三角形三边的距离之和为\\(6\\)，即\\(OD + OE + OF = 6\\)，由于\\(OD = OE = OF\\)，所以\\(OD = OE = OF = 6\\div3 = 2\\)。\n    - 如图：\n![img](https://p3-hippo-sign.byteimg.com/tos-cn-i-a9yeduch1e/71fd774c0d904e43938daff8431d4b54~tplv-ii0cwwkcx9-resize-crop-v1:28:33:316:194:0:0.jpeg?lk3s=6d071cf4&x-expires=2072956381&x-signature=hBdbnWpbN7p111Vzr8MkkMM%2BnHw%3D)\n2. **计算三角形面积**\n    - 三角形的周长为\\(12\\)，即\\(AB + BC + AC = 12\\)。\n    - 根据三角形面积公式，\\(\\triangle ABC\\)的面积\\(S_{\\triangle ABC}\\)可以表示为\\(\\triangle AOB\\)、\\(\\triangle BOC\\)、\\(\\triangle AOC\\)面积之和。\n    - 对于\\(\\triangle AOB\\)，其面积\\(S_{\\triangle AOB}=\\frac{1}{2}AB\\cdot OD\\)；对于\\(\\triangle BOC\\)，其面积\\(S_{\\triangle BOC}=\\frac{1}{2}BC\\cdot OE\\)；对于\\(\\triangle AOC\\)，其面积\\(S_{\\triangle AOC}=\\frac{1}{2}AC\\cdot OF\\)。\n    - 所以\\(S_{\\triangle ABC}=S_{\\triangle AOB}+S_{\\triangle BOC}+S_{\\triangle AOC}=\\frac{1}{2}AB\\cdot OD+\\frac{1}{2}BC\\cdot OE+\\frac{1}{2}AC\\cdot OF\\)。\n    - 因为\\(OD = OE = OF = 2\\)，将其代入上式可得\\(S_{\\triangle ABC}=\\frac{1}{2}(AB + BC + AC)\\cdot OD\\)。\n    - 把\\(AB + BC + AC = 12\\)，\\(OD = 2\\)代入式子，得到\\(S_{\\triangle ABC}=\\frac{1}{2}×12×2 = 12\\)。\n## 总结\n三角形的面积为\\(12\\)。",
      "category": "geometry",
      "difficulty": "medium",
      "createTime": "2025-09-12 09:30:00"
    },
    {
      "id": 1757656292855,
      "title": "求四边形面积",
      "content": "如图，在四边形 ABCD 中，\\(AB=AD,\\)\\(AC=5,∠DAB=∠DCB=90^{\\circ }\\), 求四边形 ABCD 的面积.\n![img](1757656292855_q.webp)",
      "answer": "# 💡解答\n如图,过点 A 作$AE⊥AC$,交 CB 的延长线于点E. \n![img](1757656292855_a.webp)\n$\\because ∠DAB=∠DCB=90^{\\circ },$\n$\\therefore ∠D+∠ABC=180^{\\circ }=∠ABE+∠ABC$\n$\\therefore ∠D=∠ABE.$\n又$\\because ∠DAB=∠CAE=90^{\\circ },$\n$\\therefore ∠CAD=∠EAB.$\n又$\\because AD=AB,$\n$\\therefore △ACD\\cong △AEB(ASA),$\n∴AC=AE,即$△ACE$是等腰直角三角形, \n∴四边形 ABCD 的面积与$△ACE$的面积相等. \n$\\because S_{△ACE}=\\frac {1}{2}×5×5=12.5,$\n∴四边形 ABCD 的面积为 12. 5.",
      "category": "geometry",
      "difficulty": "easy",
      "createTime": "2025-09-12 10:15:00"
    },
    {
      "id": 1757678060835,
      "title": "利用全等三角形求角的度数",
      "content": "如图，$D$、$E$是$\\triangle ABC$外两点，连接$AD$、$AE$，有$AB = AD$、$AC = AE$，$\\angle BAD = \\angle CAE = \\alpha$．连接$CD$、$BE$交于点$F$．\n（1）当$\\alpha = 40^{\\circ}$时，$\\angle DFE$的度数为____．\n（2）用含$\\alpha$的式子表示$\\angle DFE$的度数为____．\n ![img](1757678060835_q.webp)",
      "answer": "# 💡解答\n## 分析\n本题主要涉及三角形全等的判定和性质，以及三角形内角和定理、对顶角和邻补角的概念。通过证明三角形全等得到对应角相等，再利用角之间的关系求出\\(∠DFE\\)的度数。\n## 详解\n1. **（1）当\\(\\alpha = 40^{\\circ}\\)时**\n   - **证明\\(∠DAC = ∠BAE\\)**\n     因为\\(∠BAD = ∠CAE = 40^{\\circ}\\)，且\\(∠DAC = ∠BAD+∠BAC\\)，\\(∠BAE = ∠CAE + ∠BAC\\)，所以\\(∠DAC = ∠BAE\\)。\n   - **证明\\(△ADC\\cong△ABE\\)**\n     在\\(△ADC\\)和\\(△ABE\\)中，已知\\(AD = AB\\)，\\(∠DAC = ∠BAE\\)，\\(AC = AE\\)，根据全等三角形判定定理中的“边角 - 边”（SAS），可以得出\\(△ADC\\cong△ABE(SAS)\\)。\n   - **得出\\(∠D = ∠ABE\\)**\n     由于\\(△ADC\\cong△ABE\\)，根据全等三角形的性质，全等三角形的对应角相等，所以\\(∠D = ∠ABE\\)。\n   - **证明\\(∠DAG = ∠GFB = 40^{\\circ}\\)**\n     设\\(AB\\)，\\(CD\\)交于点\\(G\\)。因为\\(∠AGD\\)与\\(∠FGB\\)是对顶角，所以\\(∠AGD = ∠FGB\\)。又因为\\(∠D = ∠ABE\\)，在\\(△ADG\\)中\\(∠DAG+∠D + ∠AGD = 180^{\\circ}\\)，在\\(△FBG\\)中\\(∠GFB+∠ABE + ∠FGB = 180^{\\circ}\\)，所以\\(∠DAG = ∠GFB\\)，而\\(∠DAG = ∠BAD = 40^{\\circ}\\)，故\\(∠GFB = 40^{\\circ}\\)。\n   - **求出\\(∠DFE\\)的度数**\n     因为\\(∠GFB\\)与\\(∠DFE\\)是邻补角，即\\(∠GFB + ∠DFE = 180^{\\circ}\\)，已知\\(∠GFB = 40^{\\circ}\\)，所以\\(∠DFE = 180^{\\circ}-40^{\\circ}=140^{\\circ}\\)。\n2. **（2）用含\\(\\alpha\\)的式子表示\\(∠DFE\\)的度数**\n   - **证明\\(∠DAC = ∠BAE\\)**\n     因为\\(∠BAD = ∠CAE=\\alpha\\)，且\\(∠DAC = ∠BAD + ∠BAC\\)，\\(∠BAE = ∠CAE+∠BAC\\)，所以\\(∠DAC = ∠BAE\\)。\n   - **证明\\(△ADC\\cong△ABE\\)**\n     在\\(△ADC\\)和\\(△ABE\\)中，\\(AD = AB\\)，\\(∠DAC = ∠BAE\\)，\\(AC = AE\\)，根据“边角 - 边”（SAS）判定定理，可得\\(△ADC\\cong△ABE(SAS)\\)。\n   - **得出\\(∠D = ∠ABE\\)**\n     由\\(△ADC\\cong△ABE\\)，根据全等三角形对应角相等，可知\\(∠D = ∠ABE\\)。\n   - **证明\\(∠DAG = ∠GFB=\\alpha\\)**\n     设\\(AB\\)，\\(CD\\)交于点\\(G\\)。因为\\(∠AGD\\)与\\(∠FGB\\)是对顶角，所以\\(∠AGD = ∠FGB\\)。又因为\\(∠D = ∠ABE\\)，在\\(△ADG\\)中\\(∠DAG + ∠D+∠AGD = 180^{\\circ}\\)，在\\(△FBG\\)中\\(∠GFB+∠ABE + ∠FGB = 180^{\\circ}\\)，所以\\(∠DAG = ∠GFB\\)，而\\(∠DAG = ∠BAD=\\alpha\\)，故\\(∠GFB=\\alpha\\)。\n   - **求出\\(∠DFE\\)的度数**\n     因为\\(∠GFB\\)与\\(∠DFE\\)是邻补角，即\\(∠GFB + ∠DFE = 180^{\\circ}\\)，所以\\(∠DFE = 180^{\\circ}-\\alpha\\)。\n## 总结\n（1）当\\(\\alpha = 40^{\\circ}\\)时，\\(∠DFE\\)的度数为\\(140^{\\circ}\\)；（2）用含\\(\\alpha\\)的式子表示\\(∠DFE\\)的度数为\\(180^{\\circ}-\\alpha\\)。",
      "category": "geometry",
      "difficulty": "hard",
      "createTime": "2025-09-12 11:54:20"
    },
    {
      "id": 1758024799784,
      "title": "四边形中等腰直角三角形之外的2个三角形面积相等",
      "content": "已知 \\(\\angle BAC = \\angle DAE = 90^{\\circ}\\)，\\(AB = AC\\)，\\(AD = AE\\)，连接BC，CD，DE，BE。求证：\\(S_{\\triangle ACD}=S_{\\triangle ABE}\\)。\n![img](1758024799784_q.webp)",
      "answer": "# 💡解答\n## 分析\n 本题通过三角形面积公式和全等三角形面积相等来证明。画辅助线构造一个中介三角形，让目标2个三角形分别与中介三角形认证面积相等，最终证明目标三角形面积相等。 ## 详解\n![img](1758024799784_a.webp)\n延长线段$BA$至点$F$，使$AF = BA$，连接点$EF$。$\\triangle BAE$和$\\triangle AEF$是相邻的两个等底等高的三角形，所以它们的面积相等，即$S_{\\triangle BAE} = S_{\\triangle AEF}$。\n\n由于$AF$是$BA$的延长线，已知$\\angle BAC = 90^\\circ$，则$\\angle CAF = 90^\\circ$。已知 $\\angle AED = 90^\\circ$。\n$\\because $$\\angle CAD + \\angle DAF = 90^\\circ$\n$\\angle EAC + \\angle DAF = 90^\\circ$\n$\\therefore $$\\angle CAD = \\angle AEF$\n\n再加上线段$AF = AB = AC$，且已知条件中线段$AE = AD$。由边角边（SAS）可知$\\triangle ACD \\cong \\triangle AEF$。进而 $S_{\\triangle ACD} = S_{\\triangle AEF}$。\n\n再结合前步已经证得的$S_{\\triangle BAE} = S_{\\triangle AEF}$，最终可证得$S_{\\triangle ACD} = S_{\\triangle ABE}$。",
      "category": "geometry",
      "difficulty": "medium",
      "createTime": "2025-09-16 12:13:19"
    },
    {
      "id": 1758186154839,
      "title": "面积为2.5的三角形",
      "content": "如图，在锐角三角形$ABC$中，$∠BAC=60^{\\circ }$，$BE、CD分别为△ABC的角平分线。BE、CD 相交于点 F$。已知$BD=3,CE=2,△BFC$的面积$=2.5$，求$△BCD$的面积= ____ . \n![img](BFC2.5_q.webp)",
      "answer": "## 分析\n本题涉及角平分线的性质、三角形内角和定理、邻补角定义、全等三角形的判定与性质以及三角形面积公式。先利用角平分线性质计算找出相等角，进而证明全等三角形得出线段关系，最后根据面积公式求解。\n## 详解\n# 💡解答\n### 1. 求相关角度\n![img](BFC2.5_a.webp)\n做辅助线 \\(FG\\) 为 \\(\\angle BFC\\) 的角平分线。\n\n - 已知\\(\\angle BAC = 60^{\\circ}\\)，根据三角形内角和定理，在\\(\\triangle ABC\\)中，\\(\\angle ABC+\\angle ACB = 180^{\\circ}-\\angle BAC\\)。\n将\\(\\angle BAC = 60^{\\circ}\\)代入可得：\\(\\angle ABC+\\angle ACB = 180^{\\circ}- 60^{\\circ}=120^{\\circ}\\)。\n - 因为\\(BE\\)、\\(CD\\)分别平分\\(\\angle ABC\\)、\\(\\angle ACB\\)，所以\\(\\angle EBC+\\angle DCB=\\frac{1}{2}\\angle ABC+\\frac{1}{2}\\angle ACB=\\frac{1}{2}(\\angle ABC + \\angle ACB)\\)。\n把\\(\\angle ABC+\\angle ACB = 120^{\\circ}\\)代入得：\\(\\angle EBC+\\angle DCB=\\frac{1}{2}\\times120^{\\circ}=60^{\\circ}\\)。\n - 在\\(\\triangle BFC\\)中，由三角形内角和定理可知\\(\\angle BFC = 180^{\\circ}-(\\angle EBC+\\angle DCB)\\)。\n将\\(\\angle EBC+\\angle DCB = 60^{\\circ}\\)代入得：\\(\\angle BFC = 180^{\\circ}-60^{\\circ}=120^{\\circ}\\)。\n - 因为\\(\\angle BFC\\)与\\(\\angle BFD\\)互为邻补角，所以\\(\\angle BFD = 180^{\\circ}-\\angle BFC\\)。\n把\\(\\angle BFC = 120^{\\circ}\\)代入得：\\(\\angle BFD = 180^{\\circ}-120^{\\circ}=60^{\\circ}\\)。\n - 因为\\(FG\\)平分\\(\\angle BFC\\)，所以\\(\\angle BFG=\\frac{1}{2}\\angle BFC\\)。\n将\\(\\angle BFC = 120^{\\circ}\\)代入得：\\(\\angle BFG=\\frac{1}{2}\\times120^{\\circ}=60^{\\circ}\\)，即\\(\\angle BFD=\\angle BFG = 60^{\\circ}\\)。\n\n### 2. 证明全等三角形\n - 在\\(\\triangle BDF\\)和\\(\\triangle BGF\\)中：\n    - \\(\\angle BFD=\\angle BFG\\)（已证）；\n    - \\(BF = BF\\)（公共边）；\n    - 因为\\(BE\\)是角平分线，所以\\(\\angle DBF=\\angle GBF\\)。\n根据全等三角形判定定理“角 - 边 - 角”（ASA），可得\\(\\triangle BDF\\cong\\triangle BGF\\)，所以\\(BD = BG\\)。\n - 同理，在\\(\\triangle CEF\\)和\\(\\triangle CGF\\)中：\n    - 因为\\(EF\\)平分\\(\\angle AEC\\)，所以\\(\\angle CEF=\\angle GEF\\)；\n    - \\(EF = EF\\)（公共边）；\n    - 因为\\(FG\\)平分\\(\\angle BFC\\)，\\(\\angle EFC=\\angle EFG = 90^{\\circ}\\)（由\\(DF\\perp FG\\)，\\(EF\\perp FG\\)及角平分线性质可得）。\n根据 ASA 定理，可证明\\(\\triangle CEF\\cong\\triangle CGF\\)，所以\\(CE = CG\\)。\n\n### 3. 求\\(BC\\)的长度\n因为\\(BC = BG+CG\\)，且\\(BD = BG = 3\\)，\\(CE = CG = 2\\)，所以\\(BC = BD + CE=3 + 2 = 5\\)。\n\n### 4. 求\\(\\triangle BCD\\)的面积\n - 已知\\(S_{\\triangle BFC}=2.5\\)，设\\(\\triangle BFC\\)中\\(BC\\)边上的高为\\(h\\)。\n根据三角形面积公式\\(S=\\frac{1}{2}\\times\\text{底}\\times\\text{高}\\)，即\\(2.5=\\frac{1}{2}\\times5\\times h\\)。\n解方程\\(2.5=\\frac{1}{2}\\times5\\times h\\)：\n\\[\n\\begin{align*}\n\\frac{1}{2}\\times5\\times h&=2.5\\\\\n\\frac{5h}{2}&=2.5\\\\\n5h&=2.5\\times2\\\\\n5h&=5\\\\\nh&=1\n\\end{align*}\n\\]\n - 对于\\(\\triangle BGF\\)，以\\(BG = 3\\)为底，高与\\(\\triangle BFC\\)相同（均为\\(h = 1\\)）。\n根据三角形面积公式可得其面积为\\(S_{\\triangle BGF}=\\frac{1}{2}\\times3\\times1 = 1.5\\)。\n - 又因为\\(\\triangle BGF\\cong\\triangle BDF\\)，所以\\(S_{\\triangle BDF}=S_{\\triangle BGF}=1.5\\)。\n - 则\\(S_{\\triangle BCD}=S_{\\triangle BDF}+S_{\\triangle BFC}=1.5 + 2.5 = 4\\)。\n\n综上，\\(BC\\)的长度为\\(5\\)，\\(\\triangle BCD\\)的面积为\\(4\\)。",
      "category": "geometry",
      "difficulty": "easy",
      "createTime": "2025-09-18 09:02:34"
    },
    {
      "id": 1758592971518,
      "title": "求\\(\\angle EAN\\)的度数",
      "content": "在$\\triangle ABC$中,AB 边的垂直平分线交 AB 于点 D,交 BC 于点 E.AC 边的垂直平分线交 AC 于点 M,交 BC 于点 N. \n（1）如图,若$∠BAC=96^{\\circ }$,则$∠EAN$的度数为____; \n![img](https://qb-oss.bytededu.cn/file/8c97b3a139d6ac6b62f7ec66fea9d32d_base64.jpg)\n \n（2）如图,若$∠BAC=80^{\\circ }$,则$∠EAN$的度数为____; \n![img](https://qb-oss.bytededu.cn/file/7b2932367ab751ce365c0e9eaa0b763a_base64.jpg)\n \n（3）若$∠BAC$的度数为$\\alpha (\\alpha ≠90^{\\circ })$,用含α的式子表示$∠EAN$的度数.",
      "answer": "### （1）求解\\(\\angle EAN\\)的度数\n- 因为\\(DE\\)是\\(AB\\)边的垂直平分线，所以\\(AE = BE\\)，根据等腰三角形的性质，\\(\\angle B=\\angle BAE\\)。\n- 同理，\\(MN\\)是\\(AC\\)边的垂直平分线，所以\\(AN = CN\\)，\\(\\angle C=\\angle CAN\\)。\n- 在\\(\\triangle ABC\\)中，\\(\\angle B+\\angle C = 180^{\\circ}-\\angle BAC=180^{\\circ} - 96^{\\circ}=84^{\\circ}\\)。\n- 所以\\(\\angle BAE+\\angle CAN=\\angle B+\\angle C = 84^{\\circ}\\)。\n- 则\\(\\angle EAN=\\angle BAC - (\\angle BAE+\\angle CAN)=96^{\\circ}-84^{\\circ}=12^{\\circ}\\)。\n\n### （2）求解\\(\\angle EAN\\)的度数\n- 因为\\(DE\\)是\\(AB\\)边的垂直平分线，所以\\(AE = BE\\)，\\(\\angle B=\\angle BAE\\)。\n- 同理，\\(MN\\)是\\(AC\\)边的垂直平分线，所以\\(AN = CN\\)，\\(\\angle C=\\angle CAN\\)。\n- 在\\(\\triangle ABC\\)中，\\(\\angle B+\\angle C = 180^{\\circ}-\\angle BAC=180^{\\circ}-80^{\\circ}=100^{\\circ}\\)。\n- 所以\\(\\angle BAE+\\angle CAN=\\angle B+\\angle C = 100^{\\circ}\\)。\n- 则\\(\\angle EAN=\\angle BAE+\\angle CAN-\\angle BAC = 100^{\\circ}-80^{\\circ}=20^{\\circ}\\)。\n\n### （3）用含\\(\\alpha\\)的式子表示\\(\\angle EAN\\)的度数并证明\n- **结论**：当\\(0^{\\circ}<\\alpha<90^{\\circ}\\)时，\\(\\angle EAN = 180^{\\circ}- 2\\alpha\\)；当\\(90^{\\circ}<\\alpha<180^{\\circ}\\)时，\\(\\angle EAN=2\\alpha - 180^{\\circ}\\)。\n- **证明**：\n    - 因为\\(DE\\)是\\(AB\\)边的垂直平分线，所以\\(AE = BE\\)，根据等腰三角形的性质，\\(\\angle B=\\angle BAE\\)。\n    - 同理，\\(MN\\)是\\(AC\\)边的垂直平分线，所以\\(AN = CN\\)，\\(\\angle C=\\angle CAN\\)。\n    - 在\\(\\triangle ABC\\)中，\\(\\angle B+\\angle C=180^{\\circ}-\\alpha\\)，所以\\(\\angle BAE+\\angle CAN=\\angle B+\\angle C = 180^{\\circ}-\\alpha\\)。\n    - 当\\(0^{\\circ}<\\alpha<90^{\\circ}\\)时，\\(\\angle EAN = 180^{\\circ}-(\\angle BAE+\\angle CAN)=180^{\\circ}-(180^{\\circ}-\\alpha)=180^{\\circ}- 2\\alpha\\)（此时\\(\\angle BAE+\\angle CAN>\\angle BAC\\)，\\(\\angle EAN\\)是\\(\\angle BAE\\)与\\(\\angle CAN\\)重叠部分之外的角）。\n    - 当\\(90^{\\circ}<\\alpha<180^{\\circ}\\)时，\\(\\angle EAN=(\\angle BAE+\\angle CAN)-\\angle BAC=(180^{\\circ}-\\alpha)-\\alpha=2\\alpha - 180^{\\circ}\\)（此时\\(\\angle BAE+\\angle CAN<\\angle BAC\\)，\\(\\angle EAN\\)是\\(\\angle BAC\\)减去\\(\\angle BAE\\)与\\(\\angle CAN\\)的和）。",
      "category": "geometry",
      "difficulty": "medium",
      "createTime": "2025-09-23 02:02:51"
    },
    {
      "id": 1758631842055,
      "title": "等腰三角形中的等腰三角形",
      "content": "在\\(\\triangle ABC\\)中，\\(BC = AC\\)，\\(\\angle ACB = 120^{\\circ}\\)，点\\(D\\)在\\(AB\\)上，点\\(E\\)在\\(AC\\)上，且\\(\\angle CDE = 30^{\\circ}\\)。\n(1)若\\(DE\\parallel BC\\)，判断\\(\\triangle ACD\\)的形状，并说明理由；若\\(\\angle BCD = 15^{\\circ}\\)，求\\(\\angle EDA\\)的度数。\n(2)请你添加一个条件，使得\\(\\triangle AED\\cong\\triangle BDC\\)，并说明理由。\n(3)当\\(\\triangle CDE\\)为等腰三角形时，求\\(\\angle AED\\)的度数。\n![img](1758631842055_q.webp)",
      "answer": "# 💡解答\n## 分析\n本题主要涉及三角形的内角和定理、平行线的性质、全等三角形的判定以及等腰三角形的性质。\n1. 对于第一问，根据平行线的性质求出相关角度，再利用三角形内角和求出\\(∠EDA\\)。\n2. 第二问通过添加条件，利用三角形内角和与外角性质得到对应角相等，结合已知边相等，依据全等三角形判定定理证明。\n3. 第三问分情况讨论等腰三角形\\(△CDE\\)的不同情况，从而求出\\(∠AED\\)的度数。\n## 详解\n1. **求\\(△ACD\\)的形状和\\(∠EDA\\)的度数**\n    - **求\\(△ACD\\)的形状**\n        - 因为\\(DE\\parallel BC\\)，根据两直线平行，内错角相等，所以\\(∠BCD = ∠CDE = 30^{\\circ}\\)。\n        - 已知\\(∠ACB = 120^{\\circ}\\)，那么\\(∠ACD = ∠ACB - ∠BCD = 120^{\\circ}-30^{\\circ}=90^{\\circ}\\)。\n        - 有一个角是\\(90^{\\circ}\\)的三角形是直角三角形，所以\\(△ACD\\)的形状为直角三角形。\n    - **求\\(∠EDA\\)的度数**\n        - 因为\\(BC = AC\\)，\\(∠ACB = 120^{\\circ}\\)，根据等腰三角形两底角相等以及三角形内角和为\\(180^{\\circ}\\)，可得\\(∠A = ∠B=\\frac{180^{\\circ}-120^{\\circ}}{2}=30^{\\circ}\\)。\n        - 已知\\(∠BCD = 15^{\\circ}\\)，在\\(△BCD\\)中，根据三角形内角和为\\(180^{\\circ}\\)，可得\\(∠CDA = 180^{\\circ}-∠B - ∠BCD=180^{\\circ}-30^{\\circ}-15^{\\circ}=45^{\\circ}\\)。\n        - 因为\\(∠CDE = 30^{\\circ}\\)，所以\\(∠EDA = ∠CDA - ∠CDE = 45^{\\circ}-30^{\\circ}=15^{\\circ}\\)。\n2. **证明\\(△AED\\cong △BDC\\)**\n        - 已知\\(BC = AC\\)，\\(∠ACB = 120^{\\circ}\\)，所以\\(∠A = ∠B = 30^{\\circ}\\)。\n        - 因为\\(∠CDB\\)是\\(△ACD\\)的一个外角，根据三角形外角等于不相邻两个内角之和，所以\\(∠CDB=∠A + ∠ACD\\)。\n        - 又因为\\(∠AED = ∠ACD + ∠CDE\\)，且\\(∠A = ∠CDE = 30^{\\circ}\\)，所以\\(∠AED = ∠BDC\\)。\n        - 在\\(△AED\\)和\\(△BDC\\)中，有\\(\\left\\{\\begin{array}{l} ∠A = ∠B\\\\ ∠AED = ∠BDC\\\\ AD = BC\\end{array}\\right.\\)。\n        - 根据两角及其中一角的对边对应相等的两个三角形全等（AAS），所以\\(△AED\\cong △BDC\\)。\n3. **讨论\\(△CDE\\)为等腰三角形时\\(∠AED\\)的度数**\n        - **情况一：当\\(CD = DE\\)时**\n            - 因为\\(∠CDE = 30^{\\circ}\\)，根据等腰三角形两底角相等，所以\\(∠DCE = ∠DEC=\\frac{180^{\\circ}-30^{\\circ}}{2}=75^{\\circ}\\)。\n            - 又因为\\(∠A = 30^{\\circ}\\)，在\\(△ADE\\)中，根据三角形内角和为\\(180^{\\circ}\\)，可得\\(∠AED = 180^{\\circ}-30^{\\circ}-45^{\\circ}=105^{\\circ}\\)。\n        - **情况二：当\\(CE = DE\\)时**\n            - 因为\\(∠CDE = 30^{\\circ}\\)，所以\\(∠DCE = ∠CDE = 30^{\\circ}\\)。\n            - 那么\\(∠AED = ∠DCE + ∠CDE = 60^{\\circ}\\)。\n        - **情况三：当\\(CD = CE\\)时**\n            - 此时\\(∠CED = ∠CDE = 30^{\\circ}\\)，但在\\(△CDE\\)中，\\(∠DCE = 180^{\\circ}-30^{\\circ}-30^{\\circ}=120^{\\circ}\\)，而\\(∠ACD = 120^{\\circ}-∠BCD\\lt120^{\\circ}\\)，所以这种情况不成立。\n        - 综上，\\(∠AED\\)的度数为\\(105^{\\circ}\\)或\\(60^{\\circ}\\)。\n## 总结\n(1) 直角，\\(15^{\\circ}\\)；\n(2) 添加条件\\(AD = BC\\)，可证明\\(△AED\\cong △BDC\\)；\n(3) \\(∠AED\\)的度数为\\(105^{\\circ}\\)或\\(60^{\\circ}\\)。",
      "category": "geometry",
      "difficulty": "medium",
      "createTime": "2025-09-23 12:50:42"
    }
  ]
};