var question_xml = {
  "exportTime": "2026-06-12T00:00:00.000Z",
  "description": "GeoGebra XML 绘图命令",
  "questions": [
    {
      "id": 1772024076546,
      "title": "初二数学基础练习9-第28题",
      "xml": "<construction>\n  <element type=\"point\" label=\"A\"><coords x=\"0.0\" y=\"3.0\" z=\"1.0\"/></element>\n  <element type=\"point\" label=\"B\"><coords x=\"-2.5\" y=\"0.0\" z=\"1.0\"/></element>\n  <element type=\"point\" label=\"C\"><coords x=\"2.5\" y=\"0.0\" z=\"1.0\"/></element>\n  <command name=\"Polygon\"><input a0=\"A\" a1=\"B\" a2=\"C\"/><output a0=\"triangleABC\"/></command>\n  <element type=\"polygon\" label=\"triangleABC\"><show object=\"true\" label=\"false\"/><objColor r=\"0\" g=\"150\" b=\"0\" alpha=\"0.15\"/></element>\n  <element type=\"point\" label=\"P\"><coords x=\"0.0\" y=\"-3.0\" z=\"1.0\"/></element>\n  <command name=\"Line\"><input a0=\"A\" a1=\"P\"/><output a0=\"lineAP\"/></command>\n  <element type=\"line\" label=\"lineAP\"><show object=\"true\" label=\"false\"/><lineStyle style=\"9\"/><objColor r=\"150\" g=\"150\" b=\"150\" alpha=\"200\"/></element>\n  <command name=\"Reflect\"><input a0=\"C\" a1=\"lineAP\"/><output a0=\"D\"/></command>\n  <command name=\"Segment\"><input a0=\"A\" a1=\"D\"/><output a0=\"segmentAD\"/></command>\n  <command name=\"Segment\"><input a0=\"B\" a1=\"D\"/><output a0=\"segmentBD\"/></command>\n  <command name=\"Intersect\"><input a0=\"segmentBD\" a1=\"lineAP\"/><output a0=\"E\"/></command>\n  <command name=\"Segment\"><input a0=\"C\" a1=\"E\"/><output a0=\"segmentCE\"/></command>\n</construction>"
    },
    {
      "id": 1769223095655,
      "title": "2026年1月海淀区八上数学期末第26题",
      "xml": "<construction>\n  <element type=\"point\" label=\"C\"><coords x=\"0.0\" y=\"0.0\" z=\"1.0\"/></element>\n  <element type=\"point\" label=\"B\"><coords x=\"4.0\" y=\"0.0\" z=\"1.0\"/></element>\n  <element type=\"point\" label=\"A\"><coords x=\"0.0\" y=\"3.0\" z=\"1.0\"/></element>\n  <command name=\"Segment\"><input a0=\"A\" a1=\"B\"/><output a0=\"segmentAB\"/></command>\n  <command name=\"Segment\"><input a0=\"B\" a1=\"C\"/><output a0=\"segmentBC\"/></command>\n  <command name=\"Segment\"><input a0=\"C\" a1=\"A\"/><output a0=\"segmentCA\"/></command>\n  <command name=\"AngleBisector\"><input a0=\"B\" a1=\"A\" a2=\"C\"/><output a0=\"bisectorAD\"/></command>\n  <command name=\"Intersect\"><input a0=\"bisectorAD\" a1=\"segmentBC\"/><output a0=\"D\"/></command>\n  <command name=\"Line\"><input a0=\"A\" a1=\"D\"/><output a0=\"lineAD\"/></command>\n  <element type=\"line\" label=\"lineAD\"><show object=\"true\" label=\"false\"/><objColor r=\"255\" g=\"0\" b=\"0\" alpha=\"255\"/></element>\n  <command name=\"PerpendicularLine\"><input a0=\"A\" a1=\"lineAD\"/><output a0=\"lineAE\"/></command>\n  <command name=\"Line\"><input a0=\"B\" a1=\"C\"/><output a0=\"lineBC\"/></command>\n  <command name=\"Intersect\"><input a0=\"lineAE\" a1=\"lineBC\"/><output a0=\"E\"/></command>\n  <command name=\"Segment\"><input a0=\"A\" a1=\"E\"/><output a0=\"segmentAE\"/></command>\n  <element type=\"segment\" label=\"segmentAE\"><show object=\"true\" label=\"false\"/><objColor r=\"0\" g=\"0\" b=\"255\" alpha=\"255\"/></element>\n</construction>"
    },
    {
      "id": 1765804056384,
      "title": "等边三角形加轴对称",
      "xml": "<construction>\n  <element type=\"point\" label=\"A\"><coords x=\"0.0\" y=\"3.0\" z=\"1.0\"/></element>\n  <element type=\"point\" label=\"B\"><coords x=\"-2.5\" y=\"0.0\" z=\"1.0\"/></element>\n  <element type=\"point\" label=\"C\"><coords x=\"2.5\" y=\"0.0\" z=\"1.0\"/></element>\n  <command name=\"Polygon\"><input a0=\"A\" a1=\"B\" a2=\"C\"/><output a0=\"triangleABC\"/></command>\n  <element type=\"polygon\" label=\"triangleABC\"><show object=\"true\" label=\"false\"/><objColor r=\"0\" g=\"150\" b=\"0\" alpha=\"0.15\"/></element>\n  <element type=\"point\" label=\"P\"><coords x=\"1.5\" y=\"1.5\" z=\"1.0\"/></element>\n  <command name=\"Line\"><input a0=\"A\" a1=\"P\"/><output a0=\"lineAP\"/></command>\n  <element type=\"line\" label=\"lineAP\"><show object=\"true\" label=\"false\"/><lineStyle style=\"9\"/><objColor r=\"150\" g=\"150\" b=\"150\" alpha=\"200\"/></element>\n  <command name=\"Reflect\"><input a0=\"B\" a1=\"lineAP\"/><output a0=\"D\"/></command>\n  <command name=\"Line\"><input a0=\"D\" a1=\"C\"/><output a0=\"lineDC\"/></command>\n  <command name=\"Intersect\"><input a0=\"lineDC\" a1=\"lineAP\"/><output a0=\"E\"/></command>\n  <command name=\"Segment\"><input a0=\"B\" a1=\"E\"/><output a0=\"segmentBE\"/></command>\n  <command name=\"Segment\"><input a0=\"D\" a1=\"E\"/><output a0=\"segmentDE\"/></command>\n</construction>"
    },
    {
      "id": 1765594225221,
      "title": "对角和为180度的四边形中三角形的周长",
      "xml": "<construction>\n  <element type=\"point\" label=\"A\"><coords x=\"-3.0\" y=\"2.0\" z=\"1.0\"/></element>\n  <element type=\"point\" label=\"B\"><coords x=\"2.0\" y=\"2.0\" z=\"1.0\"/></element>\n  <element type=\"point\" label=\"C\"><coords x=\"3.0\" y=\"-1.5\" z=\"1.0\"/></element>\n  <element type=\"point\" label=\"D\"><coords x=\"-2.0\" y=\"-1.5\" z=\"1.0\"/></element>\n  <command name=\"Polygon\"><input a0=\"A\" a1=\"B\" a2=\"C\" a3=\"D\"/><output a0=\"quadABCD\"/></command>\n  <element type=\"polygon\" label=\"quadABCD\"><show object=\"true\" label=\"false\"/><objColor r=\"0\" g=\"100\" b=\"200\" alpha=\"0.1\"/></element>\n  <element type=\"point\" label=\"E\"><coords x=\"2.5\" y=\"0.5\" z=\"1.0\"/></element>\n  <element type=\"point\" label=\"F\"><coords x=\"0.0\" y=\"-1.5\" z=\"1.0\"/></element>\n  <command name=\"Segment\"><input a0=\"A\" a1=\"E\"/><output a0=\"segmentAE\"/></command>\n  <command name=\"Segment\"><input a0=\"A\" a1=\"F\"/><output a0=\"segmentAF\"/></command>\n  <command name=\"Segment\"><input a0=\"C\" a1=\"E\"/><output a0=\"segmentCE\"/></command>\n  <command name=\"Segment\"><input a0=\"C\" a1=\"F\"/><output a0=\"segmentCF\"/></command>\n  <command name=\"Segment\"><input a0=\"E\" a1=\"F\"/><output a0=\"segmentEF\"/></command>\n  <command name=\"Polygon\"><input a0=\"C\" a1=\"E\" a2=\"F\"/><output a0=\"triangleCEF\"/></command>\n  <element type=\"polygon\" label=\"triangleCEF\"><show object=\"true\" label=\"false\"/><objColor r=\"255\" g=\"100\" b=\"0\" alpha=\"0.2\"/></element>\n</construction>"
    },
    {
      "id": 1764742968821,
      "title": "2个等边三角形中的全等",
      "xml": "<construction>\n  <element type=\"point\" label=\"A\"><coords x=\"-4.0\" y=\"0.0\" z=\"1.0\"/></element>\n  <element type=\"point\" label=\"B\"><coords x=\"4.0\" y=\"0.0\" z=\"1.0\"/></element>\n  <element type=\"point\" label=\"C\"><coords x=\"0.0\" y=\"0.0\" z=\"1.0\"/></element>\n  <expression label=\"F\" exp=\"Rotate[A, 60°, C]\" type=\"point\"/>\n  <expression label=\"E\" exp=\"Rotate[B, -60°, C]\" type=\"point\"/>\n  <command name=\"Polygon\"><input a0=\"A\" a1=\"C\" a2=\"F\"/><output a0=\"triangleACF\"/></command>\n  <command name=\"Polygon\"><input a0=\"B\" a1=\"C\" a2=\"E\"/><output a0=\"triangleBCE\"/></command>\n  <element type=\"polygon\" label=\"triangleACF\"><show object=\"true\" label=\"false\"/><objColor r=\"0\" g=\"150\" b=\"0\" alpha=\"0.15\"/></element>\n  <element type=\"polygon\" label=\"triangleBCE\"><show object=\"true\" label=\"false\"/><objColor r=\"0\" g=\"100\" b=\"255\" alpha=\"0.15\"/></element>\n  <command name=\"Segment\"><input a0=\"A\" a1=\"E\"/><output a0=\"segmentAE\"/></command>\n  <command name=\"Segment\"><input a0=\"B\" a1=\"F\"/><output a0=\"segmentBF\"/></command>\n  <command name=\"Midpoint\"><input a0=\"A\" a1=\"E\"/><output a0=\"M\"/></command>\n  <command name=\"Midpoint\"><input a0=\"B\" a1=\"F\"/><output a0=\"N\"/></command>\n  <command name=\"Segment\"><input a0=\"C\" a1=\"M\"/><output a0=\"segmentCM\"/></command>\n  <command name=\"Segment\"><input a0=\"C\" a1=\"N\"/><output a0=\"segmentCN\"/></command>\n  <command name=\"Segment\"><input a0=\"M\" a1=\"N\"/><output a0=\"segmentMN\"/></command>\n</construction>"
    },
    {
      "id": 1764123730840,
      "title": "求证：AD平分∠BAE",
      "xml": "<construction>\n  <element type=\"point\" label=\"B\"><coords x=\"0.0\" y=\"0.0\" z=\"1.0\"/></element>\n  <element type=\"point\" label=\"C\"><coords x=\"6.0\" y=\"0.0\" z=\"1.0\"/></element>\n  <element type=\"point\" label=\"D\"><coords x=\"3.0\" y=\"0.0\" z=\"1.0\"/></element>\n  <element type=\"point\" label=\"A\"><coords x=\"4.5\" y=\"3.0\" z=\"1.0\"/></element>\n  <command name=\"Midpoint\"><input a0=\"D\" a1=\"C\"/><output a0=\"E\"/></command>\n  <command name=\"Reflect\"><input a0=\"A\" a1=\"E\"/><output a0=\"G\"/></command>\n  <command name=\"Segment\"><input a0=\"A\" a1=\"B\"/><output a0=\"segmentAB\"/></command>\n  <command name=\"Segment\"><input a0=\"B\" a1=\"C\"/><output a0=\"segmentBC\"/></command>\n  <command name=\"Segment\"><input a0=\"C\" a1=\"A\"/><output a0=\"segmentCA\"/></command>\n  <command name=\"Segment\"><input a0=\"A\" a1=\"D\"/><output a0=\"segmentAD\"/></command>\n  <command name=\"Segment\"><input a0=\"A\" a1=\"E\"/><output a0=\"segmentAE\"/></command>\n  <command name=\"Segment\"><input a0=\"D\" a1=\"G\"/><output a0=\"segmentDG\"/></command>\n  <element type=\"segment\" label=\"segmentAD\"><show object=\"true\" label=\"false\"/><objColor r=\"255\" g=\"0\" b=\"0\" alpha=\"255\"/></element>\n</construction>"
    },
    {
      "id": 1758631842055,
      "title": "等腰三角形中的等腰三角形",
      "xml": "<construction>\n  <element type=\"point\" label=\"A\"><coords x=\"0.0\" y=\"0.0\" z=\"1.0\"/></element>\n  <element type=\"point\" label=\"B\"><coords x=\"5.0\" y=\"0.0\" z=\"1.0\"/></element>\n  <expression label=\"C\" exp=\"Rotate[B, 30°, A]\" type=\"point\"/>\n  <command name=\"Segment\"><input a0=\"A\" a1=\"B\"/><output a0=\"segmentAB\"/></command>\n  <command name=\"Segment\"><input a0=\"B\" a1=\"C\"/><output a0=\"segmentBC\"/></command>\n  <command name=\"Segment\"><input a0=\"C\" a1=\"A\"/><output a0=\"segmentCA\"/></command>\n  <element type=\"point\" label=\"D\"><coords x=\"2.5\" y=\"0.0\" z=\"1.0\"/></element>\n  <element type=\"point\" label=\"E\"><coords x=\"3.5\" y=\"1.2\" z=\"1.0\"/></element>\n  <command name=\"Segment\"><input a0=\"D\" a1=\"E\"/><output a0=\"segmentDE\"/></command>\n  <element type=\"segment\" label=\"segmentDE\"><show object=\"true\" label=\"false\"/><lineStyle style=\"9\"/><objColor r=\"150\" g=\"150\" b=\"150\" alpha=\"200\"/></element>\n</construction>"
    },
    {
      "id": 1758592971518,
      "title": "求∠EAN的度数",
      "xml": "<construction>\n  <element type=\"point\" label=\"A\"><coords x=\"0.0\" y=\"0.0\" z=\"1.0\"/></element>\n  <element type=\"point\" label=\"B\"><coords x=\"6.0\" y=\"0.0\" z=\"1.0\"/></element>\n  <element type=\"point\" label=\"C\"><coords x=\"2.0\" y=\"4.0\" z=\"1.0\"/></element>\n  <command name=\"Segment\"><input a0=\"A\" a1=\"B\"/><output a0=\"segmentAB\"/></command>\n  <command name=\"Segment\"><input a0=\"B\" a1=\"C\"/><output a0=\"segmentBC\"/></command>\n  <command name=\"Segment\"><input a0=\"C\" a1=\"A\"/><output a0=\"segmentCA\"/></command>\n  <command name=\"PerpendicularBisector\"><input a0=\"A\" a1=\"B\"/><output a0=\"perpAB\"/></command>\n  <command name=\"Intersect\"><input a0=\"perpAB\" a1=\"segmentBC\"/><output a0=\"E\"/></command>\n  <command name=\"PerpendicularBisector\"><input a0=\"A\" a1=\"C\"/><output a0=\"perpAC\"/></command>\n  <command name=\"Intersect\"><input a0=\"perpAC\" a1=\"segmentBC\"/><output a0=\"N\"/></command>\n  <command name=\"Segment\"><input a0=\"A\" a1=\"E\"/><output a0=\"segmentAE\"/></command>\n  <command name=\"Segment\"><input a0=\"A\" a1=\"N\"/><output a0=\"segmentAN\"/></command>\n  <element type=\"segment\" label=\"segmentAE\"><show object=\"true\" label=\"false\"/><objColor r=\"255\" g=\"0\" b=\"0\" alpha=\"255\"/></element>\n  <element type=\"segment\" label=\"segmentAN\"><show object=\"true\" label=\"false\"/><objColor r=\"0\" g=\"0\" b=\"255\" alpha=\"255\"/></element>\n</construction>"
    },
    {
      "id": 1758186154839,
      "title": "面积为2.5的三角形",
      "xml": "<construction>\n  <element type=\"point\" label=\"A\"><coords x=\"0.0\" y=\"0.0\" z=\"1.0\"/></element>\n  <element type=\"point\" label=\"B\"><coords x=\"5.0\" y=\"0.0\" z=\"1.0\"/></element>\n  <element type=\"point\" label=\"C\"><coords x=\"2.0\" y=\"3.0\" z=\"1.0\"/></element>\n  <command name=\"Segment\"><input a0=\"A\" a1=\"B\"/><output a0=\"segmentAB\"/></command>\n  <command name=\"Segment\"><input a0=\"B\" a1=\"C\"/><output a0=\"segmentBC\"/></command>\n  <command name=\"Segment\"><input a0=\"C\" a1=\"A\"/><output a0=\"segmentCA\"/></command>\n  <command name=\"AngleBisector\"><input a0=\"B\" a1=\"A\" a2=\"C\"/><output a0=\"bisectorA\"/></command>\n  <command name=\"AngleBisector\"><input a0=\"A\" a1=\"B\" a2=\"C\"/><output a0=\"bisectorB\"/></command>\n  <command name=\"Intersect\"><input a0=\"bisectorA\" a1=\"bisectorB\"/><output a0=\"F\"/></command>\n  <command name=\"AngleBisector\"><input a0=\"B\" a1=\"F\" a2=\"C\"/><output a0=\"bisectorBFC\"/></command>\n  <element type=\"line\" label=\"bisectorBFC\"><show object=\"true\" label=\"false\"/><lineStyle style=\"9\"/><objColor r=\"255\" g=\"0\" b=\"0\" alpha=\"200\"/></element>\n</construction>"
    },
    {
      "id": 1758024799784,
      "title": "四边形中等腰直角三角形之外的2个三角形面积相等",
      "xml": "<construction>\n  <element type=\"point\" label=\"A\"><coords x=\"0.0\" y=\"0.0\" z=\"1.0\"/></element>\n  <element type=\"point\" label=\"B\"><coords x=\"3.0\" y=\"0.0\" z=\"1.0\"/></element>\n  <element type=\"point\" label=\"C\"><coords x=\"0.0\" y=\"3.0\" z=\"1.0\"/></element>\n  <element type=\"point\" label=\"D\"><coords x=\"-2.0\" y=\"0.0\" z=\"1.0\"/></element>\n  <element type=\"point\" label=\"E\"><coords x=\"0.0\" y=\"-2.0\" z=\"1.0\"/></element>\n  <command name=\"Polygon\"><input a0=\"A\" a1=\"B\" a2=\"C\" a3=\"D\"/><output a0=\"quadABCD\"/></command>\n  <element type=\"polygon\" label=\"quadABCD\"><show object=\"true\" label=\"false\"/><objColor r=\"0\" g=\"100\" b=\"200\" alpha=\"0.1\"/></element>\n  <command name=\"Segment\"><input a0=\"A\" a1=\"D\"/><output a0=\"segmentAD\"/></command>\n  <command name=\"Segment\"><input a0=\"A\" a1=\"E\"/><output a0=\"segmentAE\"/></command>\n  <command name=\"Segment\"><input a0=\"D\" a1=\"E\"/><output a0=\"segmentDE\"/></command>\n  <command name=\"Segment\"><input a0=\"B\" a1=\"E\"/><output a0=\"segmentBE\"/></command>\n  <command name=\"Polygon\"><input a0=\"A\" a1=\"C\" a2=\"D\"/><output a0=\"triangleACD\"/></command>\n  <command name=\"Polygon\"><input a0=\"A\" a1=\"B\" a2=\"E\"/><output a0=\"triangleABE\"/></command>\n  <element type=\"polygon\" label=\"triangleACD\"><show object=\"true\" label=\"false\"/><objColor r=\"0\" g=\"150\" b=\"200\" alpha=\"0.2\"/></element>\n  <element type=\"polygon\" label=\"triangleABE\"><show object=\"true\" label=\"false\"/><objColor r=\"255\" g=\"150\" b=\"0\" alpha=\"0.2\"/></element>\n</construction>"
    },
    {
      "id": 1757678060835,
      "title": "利用全等三角形求角的度数",
      "xml": "<construction>\n  <element type=\"point\" label=\"A\"><coords x=\"0.0\" y=\"0.0\" z=\"1.0\"/></element>\n  <element type=\"point\" label=\"B\"><coords x=\"4.0\" y=\"0.0\" z=\"1.0\"/></element>\n  <expression label=\"C\" exp=\"Rotate[B, 60°, A]\" type=\"point\"/>\n  <element type=\"point\" label=\"D\"><coords x=\"-1.5\" y=\"2.0\" z=\"1.0\"/></element>\n  <element type=\"point\" label=\"E\"><coords x=\"5.5\" y=\"2.0\" z=\"1.0\"/></element>\n  <command name=\"Polygon\"><input a0=\"A\" a1=\"B\" a2=\"C\"/><output a0=\"triangleABC\"/></command>\n  <element type=\"polygon\" label=\"triangleABC\"><show object=\"true\" label=\"false\"/><objColor r=\"0\" g=\"150\" b=\"0\" alpha=\"0.15\"/></element>\n  <command name=\"Segment\"><input a0=\"A\" a1=\"D\"/><output a0=\"segmentAD\"/></command>\n  <command name=\"Segment\"><input a0=\"A\" a1=\"E\"/><output a0=\"segmentAE\"/></command>\n  <command name=\"Segment\"><input a0=\"C\" a1=\"D\"/><output a0=\"segmentCD\"/></command>\n  <command name=\"Segment\"><input a0=\"C\" a1=\"E\"/><output a0=\"segmentCE\"/></command>\n  <command name=\"Segment\"><input a0=\"B\" a1=\"E\"/><output a0=\"segmentBE\"/></command>\n  <command name=\"Intersect\"><input a0=\"segmentCD\" a1=\"segmentBE\"/><output a0=\"F\"/></command>\n</construction>"
    },
    {
      "id": 1757656292855,
      "title": "求四边形面积",
      "xml": "<construction>\n  <element type=\"point\" label=\"A\"><coords x=\"0.0\" y=\"0.0\" z=\"1.0\"/></element>\n  <element type=\"point\" label=\"B\"><coords x=\"4.0\" y=\"0.0\" z=\"1.0\"/></element>\n  <element type=\"point\" label=\"C\"><coords x=\"3.5\" y=\"3.5\" z=\"1.0\"/></element>\n  <element type=\"point\" label=\"D\"><coords x=\"-2.5\" y=\"3.5\" z=\"1.0\"/></element>\n  <command name=\"Polygon\"><input a0=\"A\" a1=\"B\" a2=\"C\" a3=\"D\"/><output a0=\"quadABCD\"/></command>\n  <element type=\"polygon\" label=\"quadABCD\"><show object=\"true\" label=\"false\"/><objColor r=\"0\" g=\"100\" b=\"200\" alpha=\"0.15\"/></element>\n  <command name=\"Segment\"><input a0=\"A\" a1=\"C\"/><output a0=\"segmentAC\"/></command>\n  <element type=\"point\" label=\"E\"><coords x=\"-4.0\" y=\"0.0\" z=\"1.0\"/></element>\n  <command name=\"Segment\"><input a0=\"A\" a1=\"E\"/><output a0=\"segmentAE\"/></command>\n  <command name=\"PerpendicularLine\"><input a0=\"A\" a1=\"segmentAC\"/><output a0=\"perpLine\"/></command>\n  <command name=\"Line\"><input a0=\"B\" a1=\"C\"/><output a0=\"lineBC\"/></command>\n  <command name=\"Intersect\"><input a0=\"perpLine\" a1=\"lineBC\"/><output a0=\"E2\"/></command>\n  <command name=\"Segment\"><input a0=\"A\" a1=\"E2\"/><output a0=\"segmentAE2\"/></command>\n  <command name=\"Segment\"><input a0=\"E\" a1=\"E2\"/><output a0=\"segmentEE2\"/></command>\n</construction>"
    }
  ]
};